app/urls.py
from django.urls import path

from .views import IndexView, PostCreateView ,PostDetailView,PostDeleteView
from . import views
app_name = "app"

urlpatterns = [
    path("",IndexView.as_view(),name= "index"),
    path("post_create/",PostCreateView.as_view(),name="post-create"),
    path('post_detail/<int:pk>/', PostDetailView.as_view(),name = "post-detail"),
    path('post_delete/<int:pk>/', PostDeleteView.as_view(),name = "post-delete"),
]

twitter_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),    
]

app/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class User(models.Model):
    name = models.CharField("name", max_length=30)
    tweet = models.TextField("tweet", max_length=255)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)

    def __str__(self):
        return self.name    

app/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User

app/views.py
from django.contrib.messages.api import success
from django.urls.base import reverse
from django.views.generic import ListView,TemplateView, CreateView,DetailView,DeleteView
from django.shortcuts import redirect, render
from .models import User
from django.contrib import messages
from django.urls import reverse_lazy


class IndexView(ListView):
    model = User
    template_name = "app/index.html"
    context_object_name = 'tweet_list'


class PostCreateView(CreateView):
    model = User
    template_name = "app/post_create.html"
    fields = '__all__'
    
    success_url = reverse_lazy('app:index')

class PostDetailView(DetailView):
    model = User
    context_object_name = 'tweet_list'

    template_name = "app/post_detail.html"


class PostDeleteView(DeleteView):
    model = User
    context_object_name = 'tweet_list'

    template_name = "app/post_delete.html"
    
    success_url = reverse_lazy('app:index')


app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'app:post-create' %}">Tweet</a>

            </div>
          </div>
        </div>
      </nav>

        <div class="container">
 
        <div class="card">
                    {% block content %}
                    {% endblock %}
            </div>
        </div> 
    </div>
</div>
</body>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}


{% block content %}
<h1 style="text-align:center; color:white; background-color:skyblue;">{% block title %}Time_Line_Site{% endblock%}</h1>
    {% for tweet in tweet_list %}
            <div class="row">
                <div class="col">
                    <div class="cardbody"style="margin-left: 0.5em;">
                    <div class="card-title"><strong>@{{tweet.name}}</strong></span>
                        <span>{{tweet.created_at}}</span>
                        <div style="float: right"><a href="{% url 'app:post-delete' tweet.pk %}">delete</a></div>
                        <div class= "card-text" style="margin-left: 1em;" ><h5>{{ tweet.tweet|linebreaksbr }}</h5></div> 

                        </div>

                        <div class="border-bottom"></div>
                    </div>
                    </div>
                </div>

    {% endfor %}
{% endblock%}


app/templates/app/post_create.html
{% extends 'app/base.html' %}
{% load static %}


{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="input-group">
          <button type="submit" class="btn btn-primary" >Add New</button>
      </div>
    </form>
  {% endblock%}


app/templates/app/post_delete.html
{% extends 'app/base.html' %}
{% load static %}


{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col">
            <div class="cardbody"style="margin-left: 0.5em;">
            <div class="card-title"><strong>@{{tweet_list.name}}</strong></span>
                <span>{{tweet_list.created_at}}</span>
                    <div class= "card-text" style="margin-left: 1em;" >{{ tweet_list.tweet|linebreaksbr }}</div> 
                </div>
                <div class="border-bottom"></div>
            </div>
            </div>
        </div>
        
        <p style="text-align:center;">このツイートを削除しますか？</p>
        <div class="text-center">
        <button type="submit"  class="btn btn-primary" >削除</button>
        </div>
    </form>

  {% endblock%}


app/templates/app/post_detail.html
{% extends 'app/base.html' %}
{% load static %}


{% block content %}
<div class="row">
  <div class="col">
      <div class="cardbody"style="margin-left: 0.5em;">
      <div class="card-title"><strong>@{{tweet_list.name}}</strong></span>
          <span>{{tweet_list.created_at}}</span>
              <div class= "card-text" style="margin-left: 1em;" >{{ tweet_list.tweet|linebreaksbr }}</div> 
          </div>
          <div class="border-bottom"></div>
      </div>
      </div>
  </div>
  {% endblock%}
